fix: omit pgmq from `supautils.privileged_extensions`
Works better for pgmq since otherwise extension objects become owned by
`supabase_admin` and we run into permission issues, e.g.:

create extension pgmq;
select from pgmq.create('msg');
ERROR:  42501: permission denied for schema pgmq